# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "613fb85300cbed6a8a058d7d96294a70"
application_url = "https://mentor-refrigerator-seen-chicks.trycloudflare.com"
embedded = true
name = "WarrantyApp"
handle = "warrantyapp"

[build]
include_config_on_deploy = true
dev_store_url = "appwaranty.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://mentor-refrigerator-seen-chicks.trycloudflare.com/auth/callback",
  "https://mentor-refrigerator-seen-chicks.trycloudflare.com/auth/shopify/callback",
  "https://mentor-refrigerator-seen-chicks.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
